### ISSUE TITLE
Upload this data to Dune as labels

### ISSUE THREAD

**Issue by antonio-mendes** [jconorgrogan/Lost-ETH#1]
Hey @jconorgrogan !

Came across this dataset and thought it was super interesting! I was thinking it would be neat to have it on [Dune](https://dune.com/browse/dashboards) - specially on [Spellbook](https://github.com/duneanalytics/spellbook) our community built interpretation layer for blockchain data.

Am pretty sure a lot of users and analysts would find this dataset useful and could build interesting queries on top of it.

Would you be ok with me adding this data there? I would add you as a PR reviewer if you want ofc and if you have a Dune account you can be credited as the creator of the dataset ofc.

Cheers!

**Comment by jconorgrogan** [comment]
Yep of course!
